weblog/post/urls.py
from django.urls import path

from . import views

app_name = 'post'

urlpatterns = [
    path('', views.index, name='index'),
    path('posts/<int:id>/', views.detail, name='detail'),
]

weblog/weblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls')),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

weblog/post/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

from django.conf import settings


class Category(models.Model):
    name = models.CharField(
        max_length=50
    )

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return f'({self.id}) {self.name}'


class Tag(models.Model):
    name = models.CharField(
        max_length=50
    )

    def __str__(self):
        return f'({self.id}) {self.name}'


class Post(models.Model):
    title = models.CharField(
        max_length=100
    )
    body = models.TextField(
        default='',
        blank=True,
    )
    published = models.BooleanField(
        default=False
    )
    created_at = models.DateTimeField(
        default=timezone.now,
        blank=True,
    )
    image = models.ImageField(
        upload_to='post_images',
        blank=True,
        default=''
    )
    tags = models.ManyToManyField(
        Tag,
        blank=True,
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )

    def __str__(self):
        return f'({self.id}) {self.title}'

    @property
    def image_path(self):
        return self.image.url if self.image else ''


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    created_at = models.DateTimeField(
        default=timezone.now
    )
    body = models.TextField()


    def __str__(self):
        return f'({self.id} {self.body[:20]})'

class ButtonAction(models.Model):
    """
    like or dislike
    """
    LIKE = 'like'
    DISLIKE = 'dislike'
    ACTION_TYPES = (
        (LIKE, _('Like')),
        (DISLIKE, _('Dislike')),
    )
    action_type = models.CharField(
        max_length=10,
        choices=ACTION_TYPES
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )

    class Meta:
        unique_together = [
            'post', 'user'
        ]

    def __str__(self):
        return f'({self.id}) {self.action_type}'

weblog/post/views.py
from django.shortcuts import render, get_object_or_404

from .models import Post


def index(request):
    posts = Post.objects.filter(
        published=True
    )
    return render(
        request,
        'post/index.html',
        {'posts': posts}
    )

def detail(request, id):
    post = get_object_or_404(
        Post.objects.filter(published=True),
        id=id
    )
    return render(
        request,
        'post/detail.html',
        {'post': post}
    )

weblog/post/templates/post/detail.html
<html>
  <head>
    <title>{{ post.title }}</title>
  </head>
  <body>
    <h1>{{ post.title }}</h1>
    <h3>{{ post.category }}</h3>
    <h3>{{ post.created_at }}</h3>
    <div>
      <p>{{ post.body }}</p>
    </div>
    {% if post.tags.all %}
    <span>Tags:</span>
    <ul>
      {% for tag in post.tags.all %}
      <li>{{ tag.name }}</li>
      {% endfor %}
    </ul>
    {% endif %}
  </body>
</html>

weblog/post/templates/post/index.html
<html>
  <head>
    <title>Our Great Weblog</title>
  </head>
  <body>
    <ul>
      {% for post in posts %}
      <li>
        <h3>
          <a href="{% url 'post:detail' post.id %}">
            {{ post.title }}
          </a>
        </h3>
        <img src={{post.image_path }} />
        <p> {{ post.body|truncatewords:10 }}</p>
      </li>
      {% endfor %}
    </ul>
  </body>
</html>